acs_dim: 9
batch_size: 32
buffer_size: 100000
ckpt_eps: 0.13832132187514942
ckpt_steps_made: 92000
episodes_per_iter: 2
eps_decay: 0.996
eps_decay_every: 1000
eps_start: 0.2
eval_mode: true
gamma: 0.99
in_channels: 3
initial_batch_episodes: 10
iter_per_save: 20
learning_rate: 0.0007
n_iters: 200
output_dir: submission_vdn/agents
seed: 42
target_updates_freq: 15
tau: 0.005
update_every: 4
warmup_steps: 1000
